version: '3.9'
services:
  logGenerator:
    image: golang:1.16.6-alpine3.14
    container_name: logGenerator
    depends_on:
      - logReceiver
    command: sh -c "/entrypoints/wait-for/wait-for.sh logReceiver:8080 && go clean && go mod tidy && go mod vendor && go run main.go"
    volumes:
      - ./entrypoints:/entrypoints
      - ./log-generator:/app
    working_dir: /app
    links:
      - logReceiver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - say_games

  logReceiver:
    image: golang:1.16.6-alpine3.14
    container_name: logReceiver
    depends_on:
      - clickhouseServer
    command: sh -c "/entrypoints/wait-for/wait-for.sh clickhouseServer:8123 && go clean && go mod tidy && go mod vendor && go run main.go"
    volumes:
      - ./entrypoints:/entrypoints
      - ./log-receiver:/app
    working_dir: /app
    links:
      - clickhouseServer
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - say_games

  clickhouseServer:
    image: yandex/clickhouse-server
    container_name: clickhouseServer
    ports:
      - "8123:8123"
    volumes:
      - ./entrypoints/init-db:/docker-entrypoint-initdb.d
    networks:
      - say_games


networks:
  say_games:
    driver: bridge